# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 12
      uses: actions/setup-node@v4
      with:
        node-version: 12.x
        cache: 'pnpm' # Ubah cache menjadi 'pnpm'
    - name: Install pnpm
      run: npm install -g pnpm # Instal pnpm secara global
    - name: Install dependencies
      run: pnpm install --frozen-lockfile # Gunakan pnpm install dengan --frozen-lockfile
    - name: Run tests
      run: npm test # Atau pnpm test jika Anda sudah mengubah script di package.json
